// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountTableRowsActive(arg1, arg2, arg3) {
  return window['go']['main']['App']['CountTableRowsActive'](arg1, arg2, arg3);
}

export function CreateTableActive(arg1, arg2) {
  return window['go']['main']['App']['CreateTableActive'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRowActive(arg1) {
  return window['go']['main']['App']['DeleteRowActive'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DescribeTableColumnsActive(arg1, arg2) {
  return window['go']['main']['App']['DescribeTableColumnsActive'](arg1, arg2);
}

export function DisconnectActive() {
  return window['go']['main']['App']['DisconnectActive']();
}

export function DropTableActive(arg1, arg2) {
  return window['go']['main']['App']['DropTableActive'](arg1, arg2);
}

export function EmptyTableActive(arg1, arg2) {
  return window['go']['main']['App']['EmptyTableActive'](arg1, arg2);
}

export function ExportDatabaseActive(arg1) {
  return window['go']['main']['App']['ExportDatabaseActive'](arg1);
}

export function FetchTableDataActive(arg1) {
  return window['go']['main']['App']['FetchTableDataActive'](arg1);
}

export function GetActiveConnection() {
  return window['go']['main']['App']['GetActiveConnection']();
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function InsertRowActive(arg1) {
  return window['go']['main']['App']['InsertRowActive'](arg1);
}

export function ListConnections(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListConnections'](arg1, arg2, arg3);
}

export function ListHistory(arg1) {
  return window['go']['main']['App']['ListHistory'](arg1);
}

export function ListObjectsActive() {
  return window['go']['main']['App']['ListObjectsActive']();
}

export function ListSchemasActive() {
  return window['go']['main']['App']['ListSchemasActive']();
}

export function ListSnippets(arg1) {
  return window['go']['main']['App']['ListSnippets'](arg1);
}

export function ListTableInfoActive(arg1) {
  return window['go']['main']['App']['ListTableInfoActive'](arg1);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function PickSSHKeyFile() {
  return window['go']['main']['App']['PickSSHKeyFile']();
}

export function RunQueryActive(arg1) {
  return window['go']['main']['App']['RunQueryActive'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveSnippetActive(arg1, arg2) {
  return window['go']['main']['App']['SaveSnippetActive'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateRowActive(arg1) {
  return window['go']['main']['App']['UpdateRowActive'](arg1);
}
