// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function CountTableRowsActive(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CreateTableActive(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteRowActive(arg1:main.DeleteRowRequest):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DescribeTableColumnsActive(arg1:string,arg2:string):Promise<Array<model.TableColumn>>;

export function DisconnectActive():Promise<void>;

export function DropTableActive(arg1:string,arg2:string):Promise<void>;

export function EmptyTableActive(arg1:string,arg2:string):Promise<void>;

export function ExportDatabaseActive(arg1:string):Promise<string>;

export function FetchTableDataActive(arg1:main.TableDataRequest):Promise<main.TableDataResponse>;

export function GetActiveConnection():Promise<main.ActiveConnectionInfo>;

export function GetConnection(arg1:string):Promise<main.ConnectionInput>;

export function InsertRowActive(arg1:main.RowMutationRequest):Promise<void>;

export function ListConnections(arg1:string,arg2:number,arg3:number):Promise<main.ConnectionPage>;

export function ListHistory(arg1:boolean):Promise<Array<main.HistoryItem>>;

export function ListObjectsActive():Promise<Array<model.DBObject>>;

export function ListSchemasActive():Promise<Array<string>>;

export function ListSnippets(arg1:boolean):Promise<Array<main.SnippetItem>>;

export function ListTableInfoActive(arg1:string):Promise<Array<model.TableInfo>>;

export function OpenConnection(arg1:string):Promise<void>;

export function PickSSHKeyFile():Promise<string>;

export function RunQueryActive(arg1:string):Promise<main.QueryRunResponse>;

export function SaveConnection(arg1:main.ConnectionInput):Promise<main.ConnectionRow>;

export function SaveSnippetActive(arg1:string,arg2:string):Promise<main.SnippetItem>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function TestConnection(arg1:main.ConnectionInput):Promise<void>;

export function UpdateRowActive(arg1:main.RowMutationRequest):Promise<void>;
